apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.Namespace }}
  name: {{ .Values.config.html.name }}
  labels:
    {{- include "nginx-web.labels" . | nindent 4 }}
{{- if .Values.config.html.annotations }}
  annotations:
{{ toYaml .Values.controller.config.annotations | indent 4 }}
{{- end }}
data:
{{ (.Files.Glob "html/*").AsConfig | indent 2 }}