# Global overrides
namespace: nginx-web
nameOverride: ""
fullNameOverride: ""

deploy:
  name: ""
  annotations: {}

  port: 80
    
  imageRepo: nginx
  imageTag: latest
  imageDigest: ""
  imagePullPolicy: IfNotPresent

volumes:
  html:
    name: nginx-html-storage
    mount: /usr/share/nginx/html
      
config:
  html:
    name: nginx-html-config
    annotations: {}

service:
  name: ""
  annotations: {}

  http:
    enable: true
    port: 80

ingress:
  name: main-site
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

