version: "3.11"

services:
  app:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
